### PR TITLE
Add more context for Translate examples.

### PR DESCRIPTION
**Pull request by markstory**
Add additional context and real-world methods for examples in TranslateBehavior tests.

Refs #3288

### CODE REVIEW

**Comment by lorenzo** [comment]
Makes me a bit sad, but ok...

**Comment by markstory** [comment]
@lorenzo I don't think it should make you sad. People new to the framework don't know where each code block should live. I think these changes help address that confusion.

**Comment by lorenzo** [comment]
I understand the reason. It just makes it appear that everything needs to be run from a controller

**Comment by markstory** [comment]
Yeah, I agree that part is bad for experienced folks, and doesn't let us show how the parts work in isolation.

**Pull request merged**
