### PR TITLE
2.0 Change "Console & Shells" to "Console Shells & Tasks"

### PR DESCRIPTION
**Pull request by ravage84**
Refers to  #3427 

Here we have to create redirects, too, to keep the old URLs to "onsole-and-shells" working.

### CODE REVIEW

**Comment by ravage84** [comment]
Darn! My IDE has problems with the chinese translations. :anger: 

DO NOT MERGE

**Comment by ravage84** [comment]
Chinese translation fixed, ready to merge.

**Comment by markstory** [comment]
Renaming files unless its necessary should probably be avoided.

**Comment by cake17** [comment]
close this due to the new PR #3465 open

**Pull request closed without merging**
