### PR TITLE
Add a very basic build process.

### PR DESCRIPTION
**Pull request by markstory**
If the HTML doesn't build something is very wrong with a pull request. We could also look for new warnings, but that is a bit more advanced.

I figured this could at least be a starting place for getting some automated checks on documentation submissions.

### CODE REVIEW

**Comment by cake17** [comment]
:+1:

**Comment by antograssiot** [comment]
nice, let's try that

**Comment by ravage84** [comment]
:candy: 
@markstory  can this be ported over to 3.0 or do you want to get some more feedback first on how it works out?

**Comment by markstory** [comment]
@ravage84 looks like @cake17 beat me to the punch.

**Pull request merged**
