### PR TITLE
cakephp-coding-conventions.rst - add clarification into ru

### PR DESCRIPTION
**Pull request by patsuckow**
cakephp-coding-conventions.rst - add clarification into ru (The same proposal that was added yesterday to the English version (#5464))

### CODE REVIEW

**Comment by patsuckow** [comment]
Did I say something wrong?

**Comment by dereuromark** [comment]
We wouldn't know - since it is Russian :)

**Comment by patsuckow** [comment]
But my proposal in English was added to the original. And this is the same proposal, but in Russian :)

**Comment by dereuromark** [comment]
Sry, but you need to find someone that can verify your PRs then if you want to speed up things :)
Just a :+1: from someone would help - no one of us speaks russian afaik. So no one is keen to press a button and blindly merge sth that he/she doesnt understand what it means.

**Comment by patsuckow** [comment]
I understood you. But what do I do with the rest of the translations that I was going to do? no longer translate? I wanted to translate all the documentation into Russian. But friends who want to check up on me every time - I do not know such :(

**Comment by patsuckow** [comment]
Should I continue to translate the documentation or not?

**Comment by dereuromark** [comment]
Sure thing.

**Comment by patsuckow** [comment]
I will try to make sure everything is accurately translated

**Pull request merged**
