### PR TITLE
clarify Date/Time object doesn't extend DateTimeInterface anymore

### PR DESCRIPTION
**Pull request by LordSimal**
Caused by https://discourse.cakephp.org/t/comparing-date-with-datetime-in-cake-5/12166/4

### CODE REVIEW

**Comment by othercorey** [comment]
This isn't true. Chronos extends DateTimeImmutable which implements DateTimeInterface.

https://github.com/cakephp/chronos/blob/3.x/src/Chronos.php#L62

**Comment by dereuromark** [comment]
in 3.x it did, but in recent versions this has been changed, no?

**Comment by LordSimal** [comment]
but [ChronosDate](https://github.com/cakephp/chronos/blob/3.x/src/ChronosDate.php#L47) and [ChronosTime](https://github.com/cakephp/chronos/blob/3.x/src/ChronosTime.php#L26) dont.

Therefore [Date](https://github.com/cakephp/cakephp/blob/5.x/src/I18n/Date.php#L34) and [Time](https://github.com/cakephp/cakephp/blob/5.x/src/I18n/Time.php#L33) can't be compared to \DateTime instances anymore (and are now silently always returning false as can be seen in the linked discourse thread)

Only [DateTime](https://github.com/cakephp/cakephp/blob/5.x/src/I18n/DateTime.php#L34) extends Chronos and can therefore be directly compared to a \DateTime instance

**Comment by othercorey** [comment]
Ah ok. I misread Time as the previous Time/FrozenTime type which became DateTime which does implement DateTimeInterface.

**Comment by othercorey** [comment]
I would omit the `Time` type due to that confusion. We didn't have a time-only type before 5.0 and the previous Time type could be confusing.

**Comment by LordSimal** [comment]
true, I thought we had but i was wrong

**Pull request merged**
