### PR TITLE
Translation code.rst into ru

### PR DESCRIPTION
**Pull request by patsuckow**
Translation code.rst into ru

### CODE REVIEW

**Comment by patsuckow** [comment]
Tell me what I'm doing is not right. The Travis CI build failed indicates that i must first translate another document ?

**Comment by saeideng** [comment]
maybe https://travis-ci.org/cakephp/docs/builds/314274638#L762

**Comment by chinpei215** [comment]
@saeideng I think @patsuckow knows why travis reported the error. So he asked us whether he has to translate the page witch contains the running-tests section first, or not.

@patsuckow Though I have already told you my opinion on Slack, in such cases, I would commit an incomplete .rst to suppress errors, like this: https://raw.githubusercontent.com/cakephp/docs/4a4491792f192c83e7783abab81c3c1c6ef69f48/ja/core-libraries/httpclient.rst

**Comment by patsuckow** [comment]
Thanks for the help!

**Comment by chinpei215** [comment]
I will restart the build.

**Comment by chinpei215** [comment]
Build successful.

**Comment by patsuckow** [comment]
:)

**Comment by chinpei215** [comment]
Thank you for your contribution.

**Pull request merged**
