### PR TITLE
Update conventions.rst

### PR DESCRIPTION
**Pull request by Josexato**
give some more information about how to setup the join tables

### CODE REVIEW

**Comment by cleptric** [comment]
Adding an ˋidˋ column for join tables is not necessary. You just could use a composite key.

**Comment by Josexato** [comment]
@cleptric even if I want to add data to that join table?

**Comment by markstory** [comment]
I think you can have additional data on the junction table when using composite keys, but building forms is a bit more complicated. I don't think we should recommend people to add a surrogate key unless they have additional data on the junction table.

**Comment by Josexato** [comment]
I think It would be helpfull to give some more information of what to do with the intermediate table. for example I've just understood that it's not expected by the convention to create an entity for the join table unless you want to save data in that intermediate table. 

I am also wondering if adding adding a surrogate key is the only way cake allows to reference an element in the join table. if that's the case I think elaborating more regarding the definition of intermediate tables would be usefull.

**Comment by dakota** [comment]
You dont need to add a surrogate key to store or reference additional data. Having one does make form building easier, but is in no way required.

**Comment by markstory** [comment]
I'm going to tweak this post merge

**Pull request merged**
