### PR TITLE
Clarify Twig plugin loading

### PR DESCRIPTION
**Pull request by dereuromark**
Refs https://github.com/cakephp/bake/issues/391 and https://github.com/cakephp/bake/issues/381#issuecomment-368099940

### CODE REVIEW

**Comment by dereuromark** [comment]
Wait, I think the code fencing is not github style here is it?

**Comment by ADmad** [comment]
Oops yes, double tilda are needed, can you please make another PR to fix :)

**Comment by dereuromark** [comment]
Fixed in https://github.com/cakephp/docs/commit/8d203df839ab103e96f797983e99b04050595f3b

**Comment by ADmad** [comment]
Thanks

**Pull request merged**
