### PR TITLE
[en][fr][ja][pt] Corrected code sample in views.rst

### PR DESCRIPTION
**Pull request by Leo240**

### CODE REVIEW

**Comment by Leo240** [comment]
@saeideng どうも ありがとう

**Comment by chinpei215** [comment]
@Leo240 I think @saeideng doesn't speak Japanese.

**Comment by saeideng** [comment]
but I understood with translator tool  :smiley:

**Comment by Leo240** [comment]
@saeideng @chinpei215 Ok, mu suggestion was not right)

**Comment by chinpei215** [comment]
No problem.

**Pull request merged**
