### PR TITLE
Mainline CMS tutorial

### PR DESCRIPTION
**Pull request by markstory**
Continue to build the bookmarker and blog tutorials, so that incoming links work, but do not include them in the visible table of contents.

### CODE REVIEW

**Comment by jeremyharris** [comment]
@markstory the tutorial isn't finished yet, is it? Last I remember, there were issues with articles automatically being assigned to a user. I walked through the tutorial from start to finish and the application isn't finished as of yet.

I can PR changes to it to wrap up the sections if you'd like, but I'd wait to push this until it's finished.

**Comment by markstory** [comment]
@jeremyharris I thought it was done :blush: I'll go through it again and make sure it all actually works. If you know of some gaps already, pull requests would be awesome.

**Comment by jeremyharris** [comment]
@markstory No worries, maybe I miscommunicated earlier on :) I created a PR for the couple of fixes. I'll go through this again as well.

**Comment by markstory** [comment]
I think this is ready to go now. I am going to work on #5312  as a follow up change to this.

**Pull request merged**
