### PR TITLE
[ja] rm old pages from 2.x

### PR DESCRIPTION
**Pull request by cake17**

### CODE REVIEW

**Comment by markstory** [comment]
Are these translations very out of date?

**Comment by okinaka** [comment]
Yes, they are.

**Comment by cake17** [comment]
I'm double checking the files, and I erased one too fast. Please wait before merging

**Comment by cake17** [comment]
Now I think everything is correct. I think it's better to erase 2.x doc's copy paste because there's too many changes since 3.x.
The japanese translators can look at the history or 2.x branch if they want to readapt old contents

**Pull request merged**
