### PR TITLE
4.0 migration guide in Japanese

### PR DESCRIPTION
**Pull request by hgsgtk**
This is the Japanese translation of the 4.0 migration guide. Also, add ja/4-0-upgrade-guide.

This PR contains

- fix en/4-0-migration-guide
- add ja/4-0-migration-guide
- add ja/4-0-upgrade-guide

ref: https://book.cakephp.org/4/en/appendices/4-0-migration-guide.html

Notice these are some missing docs, but I want to add these docs in other PRs later because it would become with a large number of rows if I add all docs in this PR.

That's why this PR does NOT contain

- create-datetime-controls
- asset-routing
- datetime-type
- body-parser-middleware
- https-enforcer-middleware

### CODE REVIEW

**Comment by markstory** [comment]
@hgsgtk Is this ready to be merged?

**Comment by hgsgtk** [comment]
Oh sorry..., it is a half of a work. I will complete my work by tommorow.

**Comment by hgsgtk** [comment]
@markstory It's ready  to be reviewed and merged.

**Comment by hgsgtk** [comment]
I found the updates. I will add a commit.

https://github.com/cakephp/docs/pull/6387

**Comment by othercorey** [comment]
I don't know if these headers are too long, but maybe it's correct for japanese characters.

```
アップグレードツールの使用
==========================
```

**Comment by hgsgtk** [comment]
@othercorey 

For Japanese characters, two `=` or `-` are needed for 1 character like this.

https://github.com/cakephp/docs/blob/a068fbdc46ec6d83989b68460d9e7bc80100b33f/ja/phinx/commands.rst#L5

That's why there are 26 `=` for 13 characters `アップグレードツールの使用`.

```
アップグレードツールの使用
==========================
```

**Comment by othercorey** [comment]
I thought so. Thank for fixing en!

**Pull request merged**
