### PR TITLE
Wrong Version

### PR DESCRIPTION
**Pull request by mo86**
3.3 instead of 3.2

### CODE REVIEW

**Comment by dereuromark** [comment]
Thank you!

**Comment by inoas** [comment]
@antograssiot could we do that through Sphinx feature as composer_cakephp_version variable?

**Comment by antograssiot** [comment]
there is already a variable if I remember well. I'll have a look at this tonight or this we

**Comment by antograssiot** [comment]
@inoas there's no need for a variable, it is only used once and will make it harder for people to update it in my opinion

**Comment by inoas** [comment]
okay. I'd have put the variable next to where we got the php version defined. So you got a few variables that all get changed at once (or not).

**Comment by antograssiot** [comment]
we probably won't upgrade the min php version on each minor release...

**Pull request merged**
