### PR TITLE
4.next > 5.x merge

### PR DESCRIPTION
**Pull request by ndm2**

### CODE REVIEW

**Comment by othercorey** [comment]
This is an existing error. The 4.x references need to be removed.

**Comment by ndm2** [comment]
Yeah, I may have asked this before, but is the request handler component removal still planned for 5.x? The code is currently still present, and there's no mention in the 5.x migration guide.

**Comment by othercorey** [comment]
@markstory Can we remove the request handler docs?

**Comment by markstory** [comment]
> @markstory Can we remove the request handler docs?

We should be able to, it is also slated for removal in 5.x. I can get it removed in 5.x and update the docs though.

**Pull request closed without merging**
