### PR TITLE
Update text.rst

### PR DESCRIPTION
**Pull request by AdrienCS**
Fixed quotes in example.

### CODE REVIEW

**Comment by dereuromark** [comment]
Why? the quotes were correct, `'` is encouraged and recommended over `"`.

**Comment by AdrienCS** [comment]
Yeah sure but in the example it causing error because of the " j'ai " word.
Another solution would be escaping this way : " j\'ai "

**Comment by dereuromark** [comment]
Yeah, in that case usually one escapes the ' char.
Either way works :)

**Comment by AdrienCS** [comment]
The problem is if you use the translate function : 
```php
echo __("J'ai.");
```

You will have a `.po` like : 
```po
msgid "J'ai"
msgstr "I have"
```

If you escape you will have : 
```po
msgid "J\'ai"
msgstr "I have"
```

**Comment by dereuromark** [comment]
Are you sure? That sounds like a core issue to me, the escape char should not bubble up further, especially not for the PO file content. It would result in non-matching (broken) translations.

**Comment by AdrienCS** [comment]
Tried, i'm wrong. ಠ_ಠ

**Comment by dereuromark** [comment]
OK, no problem. Thanks for confirming.

**Pull request merged**
