### PR TITLE
Explain that master is not for 3.x

### PR DESCRIPTION
**Pull request by dereuromark**
We should do the same for 3.0 branch then.
This should clarify some beginners confusion on why cakephp/cakephp master does not match the docs one.

### CODE REVIEW

**Comment by jhli** [comment]
Can't the branch names be changed?

**Comment by dereuromark** [comment]
@jhli It could, but that might break existing PRs and all links from outside if existent.

**Comment by ravage84** [comment]
The opposite message should be placed into the 3.0 branch, just to route back the people wanting to contribute to the 2.x docs.

I wish you could annotate branches on a Git repo level...

**Comment by markstory** [comment]
Changing the branch names will likely break the deployment tooling. That is the main reason I've not done it yet.

**Comment by jhli** [comment]
Could a new repo like cakephp/book and some mirroring help out? For 4.x?

**Pull request merged**
