### PR TITLE
[pt] Migration guide translation

### PR DESCRIPTION
**Pull request by andtxr**

### CODE REVIEW

**Comment by antograssiot** [comment]
@andtxr you have some build warning. Could you fix them or should we do it post merge?

```
/home/travis/build/cakephp/docs/pt/appendices/3-0-migration-guide.rst:17: ERROR: Unknown directive type "atenção".
.. atenção::
    O CakePHP 3.0 não irá funcionar se você não atender aos requisitos acima.
/home/travis/build/cakephp/docs/pt/appendices/3-0-migration-guide.rst:1205: WARNING: Title underline too short.
Pasta & Arquivos
-------------
/home/travis/build/cakephp/docs/pt/appendices/3-0-migration-guide.rst:1205: WARNING: Title underline too short.
Pasta & Arquivos
-------------
/home/travis/build/cakephp/docs/pt/appendices/3-0-migration-guide.rst:1276: ERROR: Unknown directive type "aviso".
.. aviso::
    Dados encriptados com Security::encrypt() em versões anteriores não são
    compatíveis com a implementação openssl. Você deve :ref:`definir a
    implementação como mcrypt <force-mcrypt>` quando fizer atualização.
```

There might be more but you can see them in the travis build now

**Comment by andtxr** [comment]
@antograssiot right now I am traveling. I will check it when come back! :+1:

**Comment by cake17** [comment]
@andtxr I can take care of the build warnings if you want?

**Comment by cake17** [comment]
I close this because  #3473 is now open.
Thanks to @andtxr and @felipevr for your work !!

**Pull request closed without merging**
