### PR TITLE
bump minimal php version

### PR DESCRIPTION
**Pull request by antograssiot**

### CODE REVIEW

**Comment by inoas** [comment]
Thanks!

p.s.: Is there no way to specify min and max version globally?

**Comment by antograssiot** [comment]
@ionas I don't think so, but i didn't search in last version.
If you wish to help http://www.sphinx-doc.org/

**Comment by inoas** [comment]
I don't know Sphinx nor Make files but maybe one / a combination could help?
I took a look at the Sphinx docs and found this:
http://www.sphinx-doc.org/en/stable/faq.html#how-do-i
```
... add global substitutions or includes?
Add them in the rst_epilog config value.
```
Ref: http://www.sphinx-doc.org/en/stable/config.html#confval-rst_epilog

Could this help?

**Comment by markstory** [comment]
The `rst_epilog` might work well. Its worth trying at least.

**Comment by antograssiot** [comment]
will try that thx

**Comment by antograssiot** [comment]
`rst_epilog` does the trick pretty well, good to know. Thanks to both of you @inoas @markstory

**Comment by markstory** [comment]
Nice work @antograssiot

**Pull request merged**
