### PR TITLE
Remove all references to requestAction().

### PR DESCRIPTION
**Pull request by ADmad**
It's best that new users are not aware of this feature.

### CODE REVIEW

**Comment by dereuromark** [comment]
This can only be merged once 3.3 stable is released, right?

**Comment by ADmad** [comment]
It can be merged now too imo. Just because it's available in code doesn't mean we need to advertise it :)

**Comment by josegonzalez** [comment]
I'd like to replace it with a notice pointing people towards view cells.

**Comment by markstory** [comment]
I'm a big :+1:. Lets not advertise what we think are bad patterns. I'll mark the method as deprecated in the 3.next branch.

**Pull request merged**
