### PR TITLE
[en] control() example corrected

### PR DESCRIPTION
**Pull request by Leo240**

### CODE REVIEW

**Comment by ravage84** [comment]
Refs: https://api.cakephp.org/3.4/class-Cake.View.Helper.FormHelper.html#_input & https://api.cakephp.org/3.4/class-Cake.View.Helper.FormHelper.html#_control

**Comment by ravage84** [comment]
Spasibo! Keep up the good work:

**Comment by Leo240** [comment]
@ravage84 👍

**Comment by inoas** [comment]
Last time I added such a change I was adviced to keep an example for both (at least one)

**Pull request merged**
