### PR TITLE
create a folder skeleton for the arabic language translations

### PR DESCRIPTION
**Pull request by azzenovic**
please create folder skeleton for the arabic language translations . I will be in charge of the arabic translation of the cakephp docs for cake 3.xx and later on 2.xx

### CODE REVIEW

**Comment by ravage84** [comment]
Hi @azzenovic 

So you want to start the Arabic translation of both, the 2.x and 3.x Cookbook?
Besides yourself, how many documentation helpers do you have at hand?

**Comment by azzenovic** [comment]
for now I will go with 3.x cookbook since it's the future of cake . Besides, it's the version I  am using for my web projects . I am currently alone but I can get some help if needed. Either way I will really wanna work on the docs. Thank you!

**Comment by ravage84** [comment]
We appreciate your wish to contribute, but you will need some help to get this done.
I don't want to discourage you but nobody needs a half translated documentation or outdated documentation translation.

We've had people starting a translation in the past, abandoning it a few months later due to whatever reasons.

So, personally, I would appreciate it, if you could get at least two other Arabic speaking people on your ship before starting it.

What I can offer you is that you can write a call for help in our [official Facebook group](https://www.facebook.com/groups/cake.community/?ref=bookmarks).
May be use [other channels](http://cakephp.org/get-involved), too:

**Comment by azzenovic** [comment]
sure. thanks for the tip!

**Comment by dereuromark** [comment]
Closing until PR is opened.

**Pull request closed without merging**
