### PR TITLE
Fixed translation in model.rst

### PR DESCRIPTION
**Pull request by thekaduu**
## Grammatical and Syntax erros
Contained grammatical and syntax errors in the Portuguese language , after a review it spotted and corrected.

### CODE REVIEW

**Comment by markstory** [comment]
There are some conflicts that will need to be fixed before this can be merged.

**Comment by andtxr** [comment]
I would try to clone this repo to resolve the conflicts, but where is it? Github says unknown repository. Is it private?

**Comment by thekaduu** [comment]
I resolved in another PullRequest Thanks

**Comment by cake17** [comment]
I close this then

**Pull request closed without merging**
