### PR TITLE
Update code-generation-with-bake.rst

### PR DESCRIPTION
**Pull request by AlaaAttya**
highlight "cake bake" command

### CODE REVIEW

**Comment by dereuromark** [comment]
Doesn't it need double backticks?

**Comment by AlaaAttya** [comment]
double brackets why?

**Comment by dereuromark** [comment]
Check the source code and other occurrences. Otherwise it is a link, not a code piece.

**Comment by cake17** [comment]
because it's not markdown, it's ReST. See http://book.cakephp.org/3.0/en/contributing/documentation.html#inline-markup

**Comment by AlaaAttya** [comment]
@dereuromark oooh sorry, you're right. just did

**Pull request merged**
