### PR TITLE
Add example for find(list) with joinable associations.

### PR DESCRIPTION
**Pull request by markstory**
Refs #2626

### CODE REVIEW

**Comment by lorenzo** [comment]
This is not correct, the method operates in n entities and not on the raw statement values. Therefor the keys should be title and author.name

**Comment by jadb** [comment]
Why title? What have I misunderstood?

**Comment by antograssiot** [comment]
@jadb I think that code should be the following:
```php
$query = $articles->find('list', [
        'keyField' => '.id',
        'valueField' => 'author.name'
    ])->contain(['Authors']);
```

**Comment by jadb** [comment]
:dizzy_face:

**Pull request merged**
