### PR TITLE
4.next - Forward ports.

### PR DESCRIPTION
**Pull request by ndm2**
The structural changes to 4.x seem fine, so here's the same for 4.next. 5.x will follow.

### CODE REVIEW

**Comment by ndm2** [comment]
Yeah, I overlooked the epub/pdf contents files for the other languages. Very not smart :(

**Comment by othercorey** [comment]
Is this a merge? We merge 4.x > 4.next > 5.x

**Comment by ndm2** [comment]
Oh, I didn't even think of the forward merges. Well, I don't necessarily want to wait for that, or put a burden on someone to do it now, I just need these changes merged for the upcoming docs-builder changes.

**Comment by othercorey** [comment]
take 2 minutes, I'll do it.

**Comment by othercorey** [comment]
done.

**Comment by ndm2** [comment]
Well, that was easy enough I guess. Let me have a quick look, 5.x had 1 or 2 conflicts for me, but I already forgot what they were 🙃

**Comment by ndm2** [comment]
Ah well, seems fine 👍

**Pull request closed without merging**
