### PR TITLE
Remove outdated info about Date and Time classes.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by LordSimal** [comment]
I'd add a separate info block where it specifically states, that you cant compare objects anymore.

**Comment by ADmad** [comment]
That could be done in a follow up PR.

**Comment by othercorey** [comment]
If we do that, we should just give an example of how to convert to a comparable object or we should add a helper to compare dates.

**Comment by LordSimal** [comment]
well to restore previous functionality one would have to convert 
```
$date <= $dateTime
```
to
```
$date->toNative() <= $dateTime->toNative() 
```
or is there a simpler way?

Adding another helper wouldn't realy solve the breaking change as far as I can tell.

Because there is already e.g. `->lessThan()` but those still require the same object type being passed down, not other types.

**Comment by ADmad** [comment]
I have added a note for `Date`. Feel free to modify the wording.

**Review by LordSimal — APPROVED** [review]

**Review by Arhell — APPROVED** [review]

**Pull request merged**
