### PR TITLE
3.0 tutos 3806

### PR DESCRIPTION
**Pull request by cake17**
This is ref to #3806.

This is a starting point for the new structure of the tutos. I created a repo https://github.com/cakephp-fr/blog-tutorial. Each commit refers to a part of the tuto (6th and 7th parts not yet done...)

I guess the best way to review this (a little bit massive sorry ....) is to build the docs locally with this branch.
Then read and test the new 7 parts of the tutos on a fresh application.

I'm sure, this contain lots of duplicate contents but this is a draft to be sure to go on the right way. Enjoy the reading !! 😄

### CODE REVIEW

**Comment by cake17** [comment]
We should probably keep old files to bookmarks to redirect to 404 page.
The old pages could maybe just contain a link to the new parts.

**Comment by HavokInspiration** [comment]
For SEO purposes, the old links should make 302 redirects (even if it is to the first part of the new tutorial).

**Comment by cake17** [comment]
@HavokInspiration We should make the redirections in nginx config ? Nothing exists in core sphinx for that purpose but I found this plugin https://pythonhosted.org/sphinxcontrib-httpdomain/

**Comment by cake17** [comment]
This PR is too big to be reviewed. I'll moved this branch [in cakephpfr/docs](https://github.com/cakephp-fr/docs-cakephp/tree/3.0-tutos-3806) in case someone wants to use it. And I'll remove this branch in this repo.

**Pull request closed without merging**
