### PR TITLE
[fr] Update conventions.rst

### PR DESCRIPTION
**Pull request by MarcoMomo**
typos corrections

### CODE REVIEW

**Comment by othercorey** [comment]
You need to rebase on latest.

**Comment by othercorey** [comment]
Please check the failing build for formatting errors.

**Comment by othercorey** [comment]
@MarcoMomo Can you fix the table formatting?

**Comment by yama** [comment]
@MarcoMomo 
https://github.com/cakephp/docs/pull/7170/commits/3099748a3c49ae8687a40519b7de546f6934e905#diff-c681c72d2a3efe41452e79f9c7a1b94575134e1865beee9577375d0e319c3fbbR261

**Pull request closed without merging**
