### PR TITLE
3.0 folder markup

### PR DESCRIPTION
**Pull request by antograssiot**
folows #2501

### CODE REVIEW

**Comment by bcrowe** [comment]
:clap:

**Comment by ADmad** [comment]
I don't particularly like all the file paths being shown as bold.

**Comment by antograssiot** [comment]
@ADmad i'm not a huge fan of this neither but it has been voted/discussed in #1152 and documentation guidelines have been edited in #2232 so just applying it.

**Comment by ADmad** [comment]
Making the paths bold didn't sound bad in theory but looking at the generated html it looks weird to me.

**Comment by bcrowe** [comment]
@ADmad @antograssiot  I agree... they are a little on the awkward side at the moment. But, with the upcoming redesign, what I was hoping for is that we can use a semi-bold 600 weight on these, which would be a much more subtle touch.

**Comment by bcrowe** [comment]
@ADmad @antograssiot A quick example to illustrate:



Not too bad, right?

**Comment by antograssiot** [comment]
@bcrowe definitly better :+1:

**Comment by ADmad** [comment]
Yip much better.

**Comment by markstory** [comment]
@bcrowe You can change the bold weight now. You don't have to wait for the redesign to complete :smile:

**Pull request merged**
