### PR TITLE
Fix a German sentence in a .po file example

### PR DESCRIPTION
**Pull request by chinpei215**
"read" is a past tense in the English sentence.

### CODE REVIEW

**Comment by ravage84** [comment]
@chinpei215 Vielen Dank! 😸

**Comment by chinpei215** [comment]
Bitte schön.

**Comment by caohuashan** [comment]
I translated some documents into Chinese. Why didn't I see the cake administrator accept my submission?

**Comment by chinpei215** [comment]
@caohuashan I think you are referring to #5112. As @markstory said [in this comment](https://github.com/cakephp/docs/pull/5112#issuecomment-316887330), you would have to rebase your work or retarget to the correct branch. Since Mark added some commit to your PR, please ask him what you should have to do in the #5112.

**Pull request merged**
