### PR TITLE
[pt] Code Generation with Bake

### PR DESCRIPTION
**Pull request by alexsmonte**
complete translation

### CODE REVIEW

**Comment by markstory** [comment]
Looks like there is a build issue. `/data/pt/bake/usage.rst:122: WARNING: undefined label: creating-a-bake-theme (if the link has no caption the label must precede a section header)`

**Comment by andtxr** [comment]
@alexsmonte thanks for the help, once the documentation files are fully translated we will merge your pull request, please take a look in the build alerts.

**Comment by andtxr** [comment]
Conflicts resolved.

**Comment by alexsmonte** [comment]
Valeu!

vou olhar agora e aprender como resolver esses conflitos, e no proximo não ter mais problemas.

**Pull request merged**
