### PR TITLE
Update and review translations to pt

### PR DESCRIPTION
**Pull request by CauanCabral**
Hi bakers,

I would like to contribute with translations of cookbook to portuguese.

Just begun, but already opened this PR as a draft, so if anyone want also could contribute.

### CODE REVIEW

**Comment by markstory** [comment]
I can't help with the translations, but I'm always happy to review for sphinx formatting and merge changes :smile:

**Comment by othercorey** [comment]
@CauanCabral This is still in Draft.

**Comment by othercorey** [comment]
Can you mark this ready for review??

**Comment by CauanCabral** [comment]
Thats a work in progress.

My intention when open this PR was to maybe attract some more portuguese speakers to help improve docs (if I put my work only on my fork, no one would know that). 

But keeping it open seens to messing out community work, so, I will close this PR.

When I finish some of editions, I will create other PR.

**Pull request closed without merging**
