### PR TITLE
[ru]Bookmarks intro full translate

### PR DESCRIPTION
**Pull request by Leo240**

### CODE REVIEW

**Comment by ravage84** [comment]
@Leo240 please comment here wher you are finished. Also remove the "WIP:" in the title, when you're ready.

**Comment by Leo240** [comment]
@ravage84 Ok

**Comment by Leo240** [comment]
@ravage84 I've done it.

**Comment by markstory** [comment]
Looks like there are only merge commits here, and no actual changes anymore.

**Comment by Leo240** [comment]
@markstory perhaps it because I don't understand well how to  work with GitDesktop

**Comment by Leo240** [comment]
Now it's done - the file has been uploaded

**Pull request merged**
