### PR TITLE
added query expression examples

### PR DESCRIPTION
**Pull request by cwbit**
Updated QueryExpression examples

* added additional examples for `addCase` to explicity show to get an `if..then..else` and a nested `if..then..elseif..then..else`
* added code snippets for each of the conditional expression functions

### CODE REVIEW

**Comment by josegonzalez** [comment]
Seems reasonable, anyone have any objections?

**Comment by markstory** [comment]
Looks great! Nice work @cwbit

**Comment by cwbit** [comment]
CakeFest hour of contribution :D

more to come...

**Comment by dereuromark** [comment]
:+1:

**Pull request merged**
