### PR TITLE
[ja][4.x] appendices/4-3-migration-guide.rst

### PR DESCRIPTION
**Pull request by yKanazawa**
https://book.cakephp.org/4/en/appendices/4-3-migration-guide.html
https://book.cakephp.org/4/ja/appendices/4-3-migration-guide.html

### CODE REVIEW

**Comment by yKanazawa** [comment]
```
...
writing output... [100%] views/themes
/home/runner/work/docs/docs/ja/appendices/4-3-migration-guide.rst:26: WARNING: undefined label: deprecation-warnings (if the link has no caption the label must precede a section header)

/home/runner/work/docs/docs/ja/appendices/4-3-migration-guide.rst:102: WARNING: unknown document: ./fixture-upgrade
/home/runner/work/docs/docs/ja/appendices/4-3-migration-guide.rst:215: WARNING: undefined label: controller-middleware (if the link has no caption the label must precede a section header)
/home/runner/work/docs/docs/ja/appendices/4-3-migration-guide.rst:240: WARNING: undefined label: converting-request-data-from-user-timezone (if the link has no caption the label must precede a section header)
/home/runner/work/docs/docs/ja/appendices/4-3-migration-guide.rst:276: WARNING: undefined label: logging-formatters (if the link has no caption the label must precede a section header)
/home/runner/work/docs/docs/ja/appendices/4-3-migration-guide.rst:301: WARNING: undefined label: httpclient-testing (if the link has no caption the label must precede a section header)
/home/runner/work/docs/docs/ja/appendices/4-3-migration-guide.rst:303: WARNING: unknown document: ./fixture-upgrade
generating indices...  genindex php-modindexdone
/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/cakephpsphinx/themes/cakephp/search.html:21: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  </p>
writing additional pages...  searchdone
copying images... [ 16%] _static/img/middleware-setup.png
copying images... [ 33%] _static/img/middleware-request.png
copying images... [ 50%] _static/img/read-the-book.jpg
copying images... [ 66%] _static/img/typical-cake-request.png
copying images... [ 83%] _static/img/validation-cycle.png
copying images... [100%] _static/img/save-cycle.png

copying static files... ... done
copying extra files... done
dumping search index in Japanese (code: ja)... done
dumping object inventory... done
build finished with problems, 8 warnings.
make[1]: *** [Makefile:44: html] Error 1
make[1]: Leaving directory '/home/runner/work/docs/docs/ja'
make: *** [Makefile:43: html-ja] Error 2
Error: Process completed with exit code 2.
```

**Review by Arhell — COMMENTED** [review]
cc @othercorey

**Comment by othercorey** [comment]
https://github.com/cakephp/docs/blob/4.x/en/appendices/fixture-upgrade.rst is missing in ja docs.

You have to add the new docs or remove the links in 4.3 migration guide.

**Comment by yKanazawa** [comment]
OK.
Add fixture-upgrade.rst as well.

**Comment by yKanazawa** [comment]
```
...
reading sources... [100%] views/themes

looking for now-outdated files... none found
pickling environment... done
/home/runner/work/docs/docs/en/contents.rst: WARNING: document isn't included in any toctree
checking consistency... done
preparing documents... done
writing output... [  0%] 404

Exception occurred:
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/docutils/writers/html5_polyglot/__init__.py", line 445, in section_title_tags
    if (ids and self.settings.section_self_link
AttributeError: 'Values' object has no attribute 'section_self_link'
The full traceback has been saved in /tmp/sphinx-err-vbcc810o.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make[1]: *** [Makefile:93: epub] Error 2
make[1]: Leaving directory '/home/runner/work/docs/docs/en'
make: *** [Makefile:51: epub-en] Error 2
Error: Process completed with exit code 2.
```

**Comment by othercorey** [comment]
@markstory any ideas?

**Comment by markstory** [comment]
That build error is coming from the english docs so it is unlikely to be caused by these changes. I don't see this same error in the server that deploys the docs so it could be an unpinned dep of sphinx that is broken.

**Pull request merged**
