### PR TITLE
Corrects variable naming convention

### PR DESCRIPTION
**Pull request by bravo-kernel**
Changes the naming convention for object variables to use lowercase/camelCase as discussed at https://github.com/cakephp/migrations/pull/79

### CODE REVIEW

**Comment by markstory** [comment]
Thanks :+1:

**Comment by antograssiot** [comment]
just figured that it as been merged into master instead of 3.0...

**Comment by dereuromark** [comment]
@antograssiot It should at least be merged "up".
But in general this could also be fine for 2.x in the future. It is easy to rewrite variables as they are usually inside the function's scope, so no BC breaking.

**Comment by dereuromark** [comment]
What about class properties? `$this->modelName` vs `$this->ModelName` and `$this->request` vs `$this->Request`. So far it seems we use the first for everything except request/response etc. 
Maybe that is also worth mentioning?

**Pull request merged**
