### PR TITLE
Update Sphinx to 1.4.5

### PR DESCRIPTION
**Pull request by cake17**
This refers to https://github.com/cakephp/docs/issues/921.

Update sphinx to the latest 1.4.5 needs the following steps for the master branch (2.x) for now (3.x will follow):
- the [phpDomain](https://github.com/markstory/sphinxcontrib-phpdomain) need some fixes made on [branch sphinx-1.4.5](https://github.com/cakephp-fr/sphinxcontrib-phpdomain/tree/sphinx-1.4.5). I made this PR https://github.com/markstory/sphinxcontrib-phpdomain/pull/1 to solve this
- Then it should be updated on the [python package website](https://pypi.python.org/pypi) with new tag 0.2.0
- This PR needs to apply
- docker images in cakephpfr/docs will need some changes made on [branch sphinx-1.4.5](https://github.com/cakephp-fr/docker/tree/sphinx-1.4.5)

Travis build fails because sphinxcontrib-phpdomain needs the update proposed in  https://github.com/markstory/sphinxcontrib-phpdomain/pull/1

Let me know if something is missing

### CODE REVIEW

**Comment by markstory** [comment]
Nice work @cake17

**Comment by markstory** [comment]
I've pushed these changes to all the other versions of the book as well.

**Comment by cake17** [comment]
Cool happy to finally close the pdf issue !! 😄

**Comment by cake17** [comment]
The cakephpfr/docs images are now updated with sphinx 1.4.5, so you can just type:
```
docker run -it --rm -v $(pwd):/data cakephpfr/docs:light make html
docker run -it --rm -v $(pwd):/data cakephpfr/docs:latest make pdf
```
etc ...

**Pull request merged**
