### PR TITLE
->addIndex() is wrong so i fix

### PR DESCRIPTION
**Pull request by hassifmohd**
should be
```
    $schema->addIndex(
      ['slug', 'title'],
      ['name' => 'slug_title']
    );
```

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
cc @markstory

**Comment by markstory** [comment]
The docs are currently correct. 

https://github.com/cakephp/cakephp/blob/b34c3faf65718f5e2007689d07ecd36e5e4f7285/src/Database/Schema/TableSchema.php#L461

Perhaps you are thinking of the migrations table object which does has the interface you have added here?

**Comment by othercorey** [comment]
@hassifmohd Do you have any feedback before we close this?

**Comment by hassifmohd** [comment]
no comment, you can close it

**Pull request closed without merging**
