### PR TITLE
Minor edits; Illustrate description() and epilog() methods

### PR DESCRIPTION
**Pull request by jeffblack360**

### CODE REVIEW

**Comment by dereuromark** [comment]
Nice! :)

**Comment by jeffblack360** [comment]
@dereuromark Thanks!  Just trying to help out!

**Comment by dereuromark** [comment]
Love the `Thank you for baking with CakePHP` part.
Sounds a little bit like the stewardess after landing :P

**Comment by jeffblack360** [comment]
Good T-Shirt material? :smile:

**Comment by dereuromark** [comment]
Or shoes. Ask @jippi :)

**Comment by markstory** [comment]
:clap:

**Pull request merged**
