### PR TITLE
Postgres -> PostgreSQL

### PR DESCRIPTION
**Pull request by ionas**
https://github.com/cakephp/docs/issues/2865

### CODE REVIEW

**Comment by rchavik** [comment]
I believe the example is using the actual `Cake\Database\Driver\Postgres` class.

If you want to fix 2865, i think the fix is to update the `meta :keywords` of the page.

**Comment by ionas** [comment]
Oh, you are right.

**Comment by ionas** [comment]
Can't find "meta :keywords" though. Where is this piece of information?

**Comment by markstory** [comment]
At the bottom of the file usually.

**Comment by ionas** [comment]
https://raw.githubusercontent.com/cakephp/docs/3.0/en/orm/database-basics.rst Can't see it anywhere in there. Maybe its my eyes/machine.

**Comment by markstory** [comment]
Its just not there. Many pages have the meta data, this one doesn't. https://raw.githubusercontent.com/cakephp/docs/3.0/en/controllers/components/authentication.rst does have it for example

**Pull request closed without merging**
