### PR TITLE
Update articles-model.rst

### PR DESCRIPTION
**Pull request by yosus**
there is no 'tags' at this point of the tutorial. In the database creation, 'tags' isn't directly linked to 'articles'.

### CODE REVIEW

**Comment by LordSimal** [comment]
See https://github.com/cakephp/docs/pull/7910

Its a N:M relation, therefore its not directly linked but still can be patched

**Comment by yosus** [comment]
but at this point of the [tutorial](https://book.cakephp.org/5/en/tutorials-and-examples/cms/database.html), where the database has been setup, calling `bin/cake bake model articles` will not create the `tags` yet.

Maybe this `tags` should be added in this later stage of the [tutorial page](https://book.cakephp.org/5/en/tutorials-and-examples/cms/tags-and-users.html#adding-tagging-to-articles), where articles & tags are being linked.

**Comment by LordSimal** [comment]
This sounds like a bug because the bake tool should generate it.

**Review by yosus — COMMENTED** [review]
sorry, the bake does create the `tags` field.  Updated to reflect what bake actually creates using the cake 5 tutorial.

**Review by Arhell — APPROVED** [review]

**Pull request merged**
