### PR TITLE
2.x note about form

### PR DESCRIPTION
**Pull request by okinaka**
Add some notes about the options of FormHelper::create().

### CODE REVIEW

**Comment by ravage84** [comment]
Refs: http://book.cakephp.org/2.0/en/appendices/2-8-migration-guide.html#deprecations

**Comment by dereuromark** [comment]
Maybe we should then remove the outdated examples and provide the correct url ones, here?

    echo $this->Form->create('User', array('action' => 'login'));

=>

    echo $this->Form->create('User', array('url' => array('action' => 'login')));

Because so far people would not see any "correct example" yet on that page.
Or would that confuse people using versions below?

**Comment by ravage84** [comment]
Agree @dereuromark 
We have done so in the past, I think.
So, I guess it's OK.

**Comment by dereuromark** [comment]
Merging this for now as it is already vital to have the information, and we can fix the rest with a 2nd PR.

**Pull request merged**
