### PR TITLE
Corrected code example in views/json and xml views

### PR DESCRIPTION
**Pull request by Spriz**
It  was messing around in articles and posts - should only be posts :-)

### CODE REVIEW

**Comment by ravage84** [comment]
Thanks. Fixed the variable name in https://github.com/cakephp/docs/commit/e5d35eafbfa701c933c7902d2f15768a1afea15d

**Comment by antograssiot** [comment]
@ravage84 We have been trying to remove all references to posts by articles in the 3.0 doc so it would be nice to keep it this way here also.

**Comment by ravage84** [comment]
Fine, then the text above needs to be revised instead.

> .. file extension such as http://example.com/posts.json.

> For example if we had posts....

https://github.com/cakephp/docs/blob/e5d35eafbfa701c933c7902d2f15768a1afea15d/en/views/json-and-xml-views.rst

**Comment by Spriz** [comment]
Fixed in new PR @ravage84 & @antograssiot

**Pull request merged**
