### PR TITLE
[4.next] Add blank line before return statements in examples

### PR DESCRIPTION
**Pull request by ravage84**
This brings the examples in line with the CakePHP coding conventions / code style standard, respectively:

https://book.cakephp.org/4/en/contributing/cakephp-coding-conventions.html#method-definition

https://github.com/cakephp/cakephp-codesniffer/blob/b12f9307475a74f8ee7625c7741fe2f54598cb0b/docs/README.md#L14 https://github.com/cakephp/cakephp-codesniffer/blob/b12f9307475a74f8ee7625c7741fe2f54598cb0b/CakePHP/Sniffs/Formatting/BlankLineBeforeReturnSniff.php

### CODE REVIEW

**Comment by dereuromark** [comment]
Looks good.

**Comment by othercorey** [comment]
Why do this only in 4.next?

**Comment by ravage84** [comment]
@othercorey I simply didn't come around doing it for 5.x, too.

Done now in #7852

**Comment by othercorey** [comment]
5.x is merged into 5.next. We don't need to make separate commits for docs.

**Pull request merged**
