### PR TITLE
[ja] Fix typo

### PR DESCRIPTION
**Pull request by auiuui**
設定して行きます→設定していきます

### CODE REVIEW

**Comment by okinaka** [comment]
@auiuui Thank you!

**Comment by Leo240** [comment]
@okinaka Hi. It's very interesting for me - what was wrong with kanji writing instead of hiragana?

**Comment by okinaka** [comment]
Although it is difficult to explain, in this context, Hiragana is in common use and readable.

http://komachi.yomiuri.co.jp/t/2015/0110/696338.htm

**Comment by Leo240** [comment]
@okinakaa Ok. ありがとうございます。

**Pull request merged**
