### PR TITLE
Initialize shell

### PR DESCRIPTION
**Pull request by sra122**
Initialize method call is required to load the models inside the Shell.

### CODE REVIEW

**Comment by garas** [comment]
`initialize()` is called by ShellDispatcher, no need to call it again. 

[src/Console/ShellDispatcher.php#L226-L230](https://github.com/cakephp/cakephp/blob/c20e268854c5642a46aa6e4ba1a7c1cf05700bea/src/Console/ShellDispatcher.php#L226-L230)

**Comment by sra122** [comment]
@garas  Yes, when we use directly the shell initialize will be called using shellDispatcher. But when you use shell call from the controller, the shellDispatcher is not used.

**Comment by dereuromark** [comment]
You should not call a shell from a controller.

**Comment by garas** [comment]
Instead you should extract code from your shell to some utility class, and use it from both shell and controller.

**Comment by dereuromark** [comment]
Or use [service layer](https://github.com/burzum/cakephp-service-layer).

**Comment by sra122** [comment]
Thank you @dereuromark  @garas

**Pull request closed without merging**
