### PR TITLE
Update request-response.rst

### PR DESCRIPTION
**Pull request by jeffblack360**
Little syntax issue: $this->request->query needs parentheses not brackets.

### CODE REVIEW

**Comment by dereuromark** [comment]
No, it was correct to use the the brackets.
The next paragraph then introduces the method:

    You can either directly access the query property, or you can use query()

**Comment by jeffblack360** [comment]
Hmmm...Brackets fails for me.

Notice (8): Undefined index: sort [APP/Controller/CategoriesController.php, line 53]
$sortreq = $this->request->query['sort'];

This works perfectly.
$sortreq = $this->request->query('sort');

**Comment by markstory** [comment]
Change seems fine. Leading people to use the methods is a good thing imo. I would like to remove the properties one day.

**Comment by jeffblack360** [comment]
@dereuromark FWIW I'm running Cake 3.0. I'll try to have a look at the code.

**Pull request merged**
