### PR TITLE
3.0 build error

### PR DESCRIPTION
**Pull request by antograssiot**
I tried to put the files in the correct directory as the docs build seems to be broken since the addition of the pictures from debug_kit (even if it was working locally).
i hope this solves the issue

### CODE REVIEW

**Comment by antograssiot** [comment]
also it seems that `basic_mvc.png` and `code_coverage.png` can be removed as I can't find any usage of them in 3.0.

**Comment by lorenzo** [comment]
Thanks, I was trying to look into why that page was missing

**Comment by markstory** [comment]
Odd, the images were working locally :cry:

**Comment by antograssiot** [comment]
@markstory yeah it was working locally but throwing warnings. anyway the build is still broken, from what I understand it might be because we can't insert gift file in the pdf. I would expect that at least it would take the first image... :disappointed:

**Pull request merged**
