### PR TITLE
Improve example.

### PR DESCRIPTION
**Pull request by markstory**
Someone on IRC found the previous example confusing.

### CODE REVIEW

**Comment by HavokInspiration** [comment]
Weren't Mailers added in 3.1 ?
Looks good to me other than that.

**Comment by antograssiot** [comment]
@HavokInspiration would you like to submit a PR to reference the 3.0 syntax/usage ? If not I can try to do it tonight (ref #3075)

**Comment by HavokInspiration** [comment]
@antograssiot There is none, the feature was fully added on 3.1. Adding a ``version added`` admonition might be the best course of action.

**Comment by HavokInspiration** [comment]
@antograssiot There is none, the feature was fully added on 3.1. Adding a ``version added`` admonition might be the best course of action. I'll submit a PR

**Comment by antograssiot** [comment]
@HavokInspiration I know that :stuck_out_tongue: What I ment is add  a versionadded tag and also mention the old Email namespace where it makes sense

**Pull request merged**
