### PR TITLE
Moving the Page Contents to the page itself instead of sidebar

### PR DESCRIPTION
**Pull request by lorenzo**
It was diffcult, even for myself that I know where the contents were,
to find information on the chapter I was reading. This has also been
the experience from many other users, specially for others comming for
the first time to the docs.

### CODE REVIEW

**Comment by lorenzo** [comment]
screen shot 2015-04-09 at 15 59 49

**Comment by ADmad** [comment]
Can we have it collapsed by default? In the screenshot you have shown it would need some scrolling to reach the content text which isn't very good either.

**Comment by lorenzo** [comment]
That's how we had it before (hidden by a button) and was moved to the sidebar since people could not find the page contents. Personally I think it is much better to have an overview of what you will learn before reading a wall of text. It is also easy to skip in most pages.

**Comment by lorenzo** [comment]
Also, it does not need scrolling if you actually click on the title you'd like to read (could be the first link, for example)

**Comment by ADmad** [comment]
okay, :+1:

**Comment by antograssiot** [comment]
:+1:

**Comment by ravage84** [comment]
Well, let's try. :+1: 
We still can change it again ;-)

**Comment by markstory** [comment]
Looks good, I've seen this in a few other sphinx based sites too.

**Comment by lorenzo** [comment]
Merging!

**Pull request merged**
