### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by carusogabriel**
I've removed all white spaces and extra lines from our documentation :smile:

### CODE REVIEW

**Comment by markstory** [comment]
Looks good to me. I'll merge this after the builds pass.

**Comment by carusogabriel** [comment]
@markstory Should I do this across `cakephp`'s repos? :smile:

**Comment by antograssiot** [comment]
I think that this is handled in other repos via the codesniffer but I might be wrong. Thanks anyway

**Comment by markstory** [comment]
There shouldn't be problems in other repos as we use phpcs to detect/prevent these issues from getting in.

**Pull request merged**
