### PR TITLE
Update request-response.rst 

### PR DESCRIPTION
**Pull request by gerrymcdonnell**
Error in documentation;
https://book.cakephp.org/4/en/controllers/request-response.html#response

$response = $response->withStringBody('My Body');
**should be**
$response = $this->response->withStringBody('My Body');

### CODE REVIEW

**Comment by dereuromark** [comment]
That would require almost all examples to be rewritten
From the context it should be clear that it is that, by assignment first.
Look at other examples above or below.

**Review by Arhell — COMMENTED** [review]
cc @markstory

**Comment by markstory** [comment]
Unless we're going to change *all* the examples, I'd rather not change just one as that will be more confusing to the reader. They are left wondering things like 'why is this example different than all the others?' or 'does this method only work with the property response?'

While the current code isn't ideal for copy/pasting it is consistent and once the reader figures out that `$this->response` and `$response` are generally interchangeable everything is great. Would it be useful to call out that assumption early on in the chapter?

**Comment by cnizzardini** [comment]
But there are examples of using `$this` so it may already be confusing to the reader. For instance: https://book.cakephp.org/4/en/controllers/request-response.html#dealing-with-content-types

**Comment by saeideng** [comment]
document is clear IMO

**Pull request closed without merging**
