### PR TITLE
delete this please

### PR DESCRIPTION
**Pull request by koyakei**

### CODE REVIEW

**Comment by okinaka** [comment]
We should target master branch for 2.x stable . 
2.8 branch is now developing for 2.x.

**Comment by koyakei** [comment]
I faild

2015-08-04 13:36 GMT+09:00 Kenshin Okinaka <notifications@github.com>:

> We should target master branch for 2.x stable .
> 2.8 branch is now developing for 2.x.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cakephp/docs/pull/3049#issuecomment-127475307>.
>



-- 
小柳圭輔 Koyanagi Keisuke <http://srns.strikingly.com/>
Skype twitter <https://twitter.com/koyakei> facebook
<https://www.facebook.com/koyakei>  = koyakei

**Comment by koyakei** [comment]
I create new request

**Comment by antograssiot** [comment]
@koyakei, please close if it's replaced by #3051

**Comment by koyakei** [comment]
close #3049

**Pull request closed without merging**
