### PR TITLE
bad variable name

### PR DESCRIPTION
**Pull request by stardisblue**
```php
        public static function parse($value)
        {
            // Parse the data from MySQL.
-            return new static($part[0],$part[1]);
+            return new static($value[0], $value[1]);
        }
```

### CODE REVIEW

**Comment by jadb** [comment]
Thanks!

**Comment by antograssiot** [comment]
Please always update the english version first for future contribution as it should stay the more accurate/up to date. thank you very much anyway.

**Comment by jadb** [comment]
My bad, looked at text above it (still in english) so I merged. Failed to notice the `fr` in the file's path.

**Comment by antograssiot** [comment]
all good @jadb :wink:

**Comment by stardisblue** [comment]
roger that @antograssiot

**Pull request merged**
