### PR TITLE
update version installation.rst

### PR DESCRIPTION
**Pull request by Iandenh**

### CODE REVIEW

**Comment by inoas** [comment]
Is there any way to serve these things from a global configuration so that we do not miss them next time around?

**Comment by markstory** [comment]
@inoas There might be. I remember @antograssiot did something to make updating the php version centralized./

**Comment by antograssiot** [comment]
We would still have to rememeber that the variable must be updated anyway. In contrary with min php version, it is only 2 occurence and on the same page but you can send a PR of you wish @inoas

**Comment by inoas** [comment]
1 place for a min. versions of PHP, MySQL, MariaDB, Postgres, CakePHP, Apache, wouldn't help? 
I could not find in sphinx documentation how to setup a global configuration file. Any pointers @antograssiot (I am also on IRC)

**Comment by antograssiot** [comment]
Config is here https://github.com/cakephp/docs/blob/3.0/config/all.py#L324-L326

**Comment by antograssiot** [comment]
By the way @inoas it is just a way to define pattern that will be replaced, not a real config but it is still interesting for the use case

**Pull request merged**
