### PR TITLE
Update en/core-libraries/email.rst

### PR DESCRIPTION
**Pull request by makallio85**

### CODE REVIEW

**Comment by antograssiot** [comment]
@makallio85 any particular reason why you're targeting 3.1 ?
Also maybe add the ``use```statement is nicer as most examples above are using it.

**Comment by makallio85** [comment]
No particular reason. This was my first commit to docs and seems like that I didn't nail it at all  :D

**Comment by antograssiot** [comment]
@makallio85, would you like to take a chance again and reopen the pull request against 3.0 as we can't change the branch unfortunately.

**Comment by makallio85** [comment]
I have to ask, but for these minor updates, which branch should i use?

**Comment by antograssiot** [comment]
3.0 directly for the book.

**Pull request closed without merging**
