### PR TITLE
add example for bake field length

### PR DESCRIPTION
**Pull request by cake17**
- ref to migrations change in https://github.com/cakephp/migrations/pull/140
- add `use Migrations\AbstractMigration;` to be consistent

### CODE REVIEW

**Comment by HavokInspiration** [comment]
Nice :+1:

However, I would add that the field length option has been added in the 1.4 release (I'll do the release once the the remaining PR gets merged).

**Comment by cake17** [comment]
Ok I'll add a note about the release. Maybe in the `migrations` file rather than in the `part-three` tutorial ?

**Comment by HavokInspiration** [comment]
Yes I agree.
An exemple in the migrations doc could be useful as well.

**Comment by cake17** [comment]
Done :smile: Let me know if this needs corrections

**Pull request merged**
