### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Leo240**
I wish to try to make russian tutorial translation - can you make a basic file structure for this?

### CODE REVIEW

**Comment by antograssiot** [comment]
@Leo240 which version of the doc do you wish to contribute because master branch is for 2.x and seeing the diff I guess it was a mistake. You probably want to target 3.x

**Comment by Leo240** [comment]
@antograssiot Yes,  you're right, simply I didn't know it.

**Comment by antograssiot** [comment]
@Leo240 I don'the see any commit from you here should we close this PR ?

**Comment by Leo240** [comment]
Yes you can

**Comment by antograssiot** [comment]
@Leo240 if you have a real intention to start russian translation, I would suggest that you come up with a (small) team and read properly [this section of the doc](https://book.cakephp.org/3.0/en/contributing/documentation.html#new-translation-language)

**Comment by Leo240** [comment]
Ok, what should I do to join the team?  I have not used github too much.

**Pull request closed without merging**
