### PR TITLE
[ja][4.x] controllers/request-response.rst

### PR DESCRIPTION
**Pull request by yKanazawa**
https://book.cakephp.org/4/en/controllers/request-response.html
https://book.cakephp.org/4/ja/controllers/request-response.html

### CODE REVIEW

**Comment by yKanazawa** [comment]
Confirmation required.
`Zend\Diactoros\UploadedFile`

**Comment by yKanazawa** [comment]
final confirmation

**Comment by yKanazawa** [comment]
Done.

**Comment by markstory** [comment]
Thank you 👍

**Pull request merged**
