### PR TITLE
Reorganizing and improving introduction section for the Query Builder chapter

### PR DESCRIPTION
**Pull request by lorenzo**

### CODE REVIEW

**Comment by lorenzo** [comment]
I recommend reading the raw file instead of the diff

**Comment by lorenzo** [comment]
Also moved the Query Builder chapter before the `Table Objects` one. Finally, moved the Map-Reduce section to another chapter where it fits best.

**Comment by markstory** [comment]
Awesome work @lorenzo

**Comment by lorenzo** [comment]
I'll merge this too, Hope the french community can forgive us for a few hours of not being in sync :P

**Pull request merged**
