### PR TITLE
3.0

### PR DESCRIPTION
**Pull request by 6120ssu**
Localisation : the cookbook says that localized string should be stored in a "default.po" file.
But it seems that localization of the core strings is not documented. These strings can be stored separately in a file named "cake.po" situated in the same folder (app/src/Locale/your_language).

### CODE REVIEW

**Comment by cake17** [comment]
@6120ssu Thanks for your message.

You first need to fork the repo, create a new branch with your commit and push it to your fork, and then make a pull request from your fork to the cakephp repo. (you're the same as 6180 from cakephp-fr.org?)

**Comment by markstory** [comment]
Closing as this cannot be merged.

**Comment by 6120ssu** [comment]
Never done that before. So I have to try again.

Yes, I am 6120 on cakephp-fr.org

William Russeil
06 43 33 55 94
 infos@wmc.fr

**Comment by cake17** [comment]
@6120ssu I opened a PR [here](https://github.com/cakephp/docs/pull/3470/files), let me know if you want to add/correct something

**Comment by 6120ssu** [comment]
Maybe we could add :
Select path for extracting : path/to/your/application/vendor

William Russeil
06 43 33 55 94
 infos@wmc.fr

**Pull request closed without merging**
