### PR TITLE
Warn about utf-8 vs ascii

### PR DESCRIPTION
**Pull request by inoas**
Ref: https://github.com/cakephp/docs/pull/4306#issuecomment-246219591

### CODE REVIEW

**Comment by dereuromark** [comment]
Is that sentence necessary? Pretty clear from the comtext imo.

**Comment by ravage84** [comment]
@dereuromark I think not, if we do it as described below:

@markstory personally, I would have preferred, that such a change is made in a minor change. Then we could put up a message in the migration guide, as I think a few people could trip over this.

**Comment by dereuromark** [comment]
>  I would have preferred, that such a change is made in a minor change

This is relict from way way back, just wrong docs, no need to discuss anything here regarding versioning IMO.

**Comment by markstory** [comment]
> @markstory personally, I would have preferred, that such a change is made in a minor change. Then we could put up a message in the migration guide, as I think a few people could trip over this.

@ravage84 The docs have just been wrong since at least 2010. The code has not changed recently.

**Comment by ravage84** [comment]
@markstory obviously, I mixed some PRs and issues here.... Moar :coffee: !

**Pull request merged**
