### PR TITLE
Translation middleware.rst into ru

### PR DESCRIPTION
**Pull request by patsuckow**
Translation middleware.rst into ru

### CODE REVIEW

**Comment by patsuckow** [comment]
"image file not readable" - does anyone know how to fix this error? :(

**Comment by markstory** [comment]
You'd have to copy the image from the english docs.

**Comment by patsuckow** [comment]
@markstory I can add pictures to my copy of the repository, but I can not add pictures to the main repository.

**Comment by markstory** [comment]
When you merge your changes they will become part of the main repository.

**Comment by patsuckow** [comment]
Well, finally, it worked :)

**Comment by markstory** [comment]
Anytime @patsuckow Thanks again :D

**Pull request merged**
