### PR TITLE
Translation Migrations to Pt-BR

### PR DESCRIPTION
**Pull request by richellyitalo**
Translation Migrations to Pt-BR

### CODE REVIEW

**Comment by markstory** [comment]
This pull request has a number of conflicts and cannot be merged. Could you resolve the conflicts and re-open the pull request?

**Comment by antograssiot** [comment]
please reopen your PR against 3.0 branch

**Comment by HavokInspiration** [comment]
Also, it seems to be a translation of the old version of the doc which was completely rewritten and reorganized a few weeks ago.

**Comment by richellyitalo** [comment]
Ok, I'm sorry.

**Pull request closed without merging**
