### PR TITLE
Use proper semver operator.

### PR DESCRIPTION
**Pull request by dereuromark**
`~3.5` is the same as `3.5.*`. no need to duplicate here.

### CODE REVIEW

**Comment by chinpei215** [comment]
Are you sure? I think ~3.5 is equivalent to >=3.5 <4.0.0.
https://getcomposer.org/doc/articles/versions.md#tilde-version-range-

**Comment by dereuromark** [comment]
Ahh, then it should be changed to ^ - to avoid further confusion. The ~ should never be used, it is a bad operator.

**Comment by chinpei215** [comment]
Yeah, operatator ^ would be better.

**Comment by ravage84** [comment]
Yes the caret operator ``^`` is preferred.

**Pull request merged**
