### PR TITLE
Optimized text added in #3352

### PR DESCRIPTION
**Pull request by OopsDoh**
I'd like to suggest more optimations in the chapter "Translate Behaviour" (CakePHP 3.x):
- Added info about the location of sql schema file at "Initializing the i18n Database Table"
- Added background info about the column length of the field "locale"
- Moved the note about language abbreviations to the paragraph "Initializing the i18n Database Table"
- Formatted the recommended language abbreviation as tip

### CODE REVIEW

**Comment by markstory** [comment]
Thanks.

**Comment by OopsDoh** [comment]
@markstory There is an error "1 check failed: The Travis CI build failed" in my last commit and your merged commit. Did I caused this by changing the path to the i18n sql schema file?

**Comment by cake17** [comment]
@OopsDoh No worries, this is not your fault. The travis.yml file was missing at the time you made the PR. This is now fixed in #3358. The next PR should pass, let us know if not and thanks for your help

**Comment by OopsDoh** [comment]
@cake17 Ok, thanks.

**Pull request merged**
