### PR TITLE
Adds CONFIG constant

### PR DESCRIPTION
**Pull request by bravo-kernel**

### CODE REVIEW

**Comment by ravage84** [comment]
Um... that really exists? Where does this constant gets defined?
Didn't find it in the 2.8 code base... :confused:

**Comment by markstory** [comment]
Huh, so it isn't. I thought it was in the earlier versions. But it looks like the constant was removed in 2.x - my bad.

**Comment by bravo-kernel** [comment]
Aha, I am still totally using `CONFIG` in Cake 3.x, should it be gone there?

Pretty please don't remove it, it's so handy :relaxed:

**Comment by ravage84** [comment]
In 3.x it is available in https://github.com/cakephp/cakephp/blob/3.1.0/tests/bootstrap.php#L43

**Comment by bravo-kernel** [comment]
Aha, you were just talking 2.x here, I was getting all confused. Thanks for clarifying.

**Comment by markstory** [comment]
Well `config/paths.php` is part of the app code, so you can have whatever constants you want. :smile:

**Comment by ravage84** [comment]
I think the root of this confusion comes from the mismatch of cakephp/cakephp (the framework) and cakephp/docs (the documentation):

cakephp/cakephp master branch = 3.x
cakephp/docs master branch = 2.x

**Comment by markstory** [comment]
@ravage84 Very likely.  I've just not had the time to sort out the various deployment and automation changes required for switching the branches around.

**Comment by bravo-kernel** [comment]
Oh f*** me, did I target the 2.x branch, excuse me :mountain_cableway:

**Comment by bravo-kernel** [comment]
OK, shall I make a new PR targeting the right 3.x branch?

**Comment by ravage84** [comment]
@bravo-kernel I stil lhaven't found the place where the ``CONFIG`` constant gets defined in the normal execution path. So, as far as I can see this constant does not exist (normally).
Can you show us where and in which version(s) this constant gets defined?
May be it's just my brain being in weekend mode....

**Comment by bravo-kernel** [comment]
Don't know where it comes from but a freshly baked Cake 3.1.0 app shows the following path to config when I add ``<?= CONFIG ?>`` to ``/src/Template/Pages/home.ctp``.

cake3app

**Comment by markstory** [comment]
@ravage84  https://github.com/cakephp/app/blob/master/config/paths.php#L47 :smile:

**Comment by ravage84** [comment]
Doh!

**Pull request merged**
