### PR TITLE
Fix error in accessors example

### PR DESCRIPTION
**Pull request by gerhard-lechner**

### CODE REVIEW

**Comment by ndm2** [comment]
What was wrong about the example? Accessors will in fact receive the value of the possibly existing field as an argument.

As it is now, the example is broken, it doesn't match the explanation around it anymore, and it will produce a PHP error because there is no `$title` property.

**Comment by gerhard-lechner** [comment]
Absolutely, I got confused here with mutators - I'm terribly sorry. The original version, which I updated a few months ago, was actually 100 % correct. Pls undo my changes, sorry again!

**Comment by dereuromark** [comment]
My bad, didnt see that the text refers to the title arg. I reverted it for now.

**Comment by dereuromark** [comment]
That said: The code is not PHP8.2+ safe, however, as null can be passed and would trigger an issue with mb_() methods.

**Comment by ndm2** [comment]
> That said: The code is not PHP8.2+ safe, however, as null can be passed and would trigger an issue with mb_() methods.

There's probably quite a few more of such cases throughout the docs, so maybe it's worth opening an issue for it so that it's not going to be forgotten.

**Pull request merged**
