### PR TITLE
[ja] update views.

### PR DESCRIPTION
**Pull request by okinaka**

### CODE REVIEW

**Comment by markstory** [comment]
@okinaka Nice work! I've added you as a collaborator on the docs team. This should will let you merge any pull requests that come in. Myself and the others do not know Japanese and your help is greatly appreciated.

**Comment by cake17** [comment]
@okinaka Nice work and welcome in the docs team :smile:

**Comment by okinaka** [comment]
Thank you!

**Comment by okinaka** [comment]
I'm very happy to join the docs team!
I will check and merge pull requests about Japanese docs.

**Pull request merged**
