### PR TITLE
Update views.rst

### PR DESCRIPTION
**Pull request by davidyell**
Added missing php tags which were preventing code highlighting

### CODE REVIEW

**Comment by davidyell** [comment]
On reflection, I'm not sure this will help. It sure does when viewing the docs in Github though :speak_no_evil:

**Comment by markstory** [comment]
PHP tags are not present in most of the class code blocks.

**Comment by davidyell** [comment]
Then I'm not sure what is causing these blocks to not be syntax highlighted.

**Comment by markstory** [comment]
Lets see if the change works then :smile:

**Pull request merged**
