### PR TITLE
Update intro.rst

### PR DESCRIPTION
**Pull request by LuizMarin**

### CODE REVIEW

**Comment by saeideng** [comment]
is this only for cake 4?
you can open PR on master first , unless for a especial change on cake 4

**Comment by othercorey** [comment]
@LuizMarin There is a contributor working on portuguese translations in 3.0 branch right now.  Can you make this commit in 3.0 branch so it doesn't conflict with their work?

Example: https://github.com/cakephp/docs/pull/6308

**Comment by LuizMarin** [comment]
@othercorey   Please, excuse me. I am working on translation for 4.x. I posted my suggestion wrong because I can't use github properly. But I'm reviewing all the 4.x translation as a way to study cake more deeply.

**Comment by othercorey** [comment]
@LuizMarin Thank you for posting a fix :) If users fix both 3.0 and 4.x, we (english speakers) cannot merge 3.0 > 4.x very easily.  That is why I ask.

**Comment by LuizMarin** [comment]
I am using the documentation that already exists for 4.x in Portuguese COMPARING WITH THE ENGLISH VERSION OF 4.x. When she refers to another version I try to adjust the document. In the current translation there are links that no longer exist and a grammar that got in the way of my studies. In addition to missing information in Portuguese that exist on the English site.  thanks for giving me some attention

**Pull request merged**
