### PR TITLE
Update helpers.rst

### PR DESCRIPTION
**Pull request by davidyell**
All other helper names are lowercase

### CODE REVIEW

**Comment by dereuromark** [comment]
I wonder if those should maybe all be uppercase? Usually, we do that if those refer to class names.

**Comment by ADmad** [comment]
Yeah using uppercase would be more consistent with how we use other names throughout the framework.

**Comment by ADmad** [comment]
There are few other instances of lowercase names too like "heading", "table" on the page.

**Comment by davidyell** [comment]
Will take a look shortly.

**Comment by ionas** [comment]
:+1: Uppercase (is there no case check?)

**Comment by dereuromark** [comment]
@lorenzo You merged the incorrect version.

**Comment by davidyell** [comment]
Oh, I've just committed the suggested amends.

https://github.com/davidyell/docs/commit/819fc68823a15a1a076ee1a3b47d108b47d10626

**Comment by davidyell** [comment]
I've put the amends in #3758

**Pull request merged**
