### PR TITLE
Recommending devs to use AppView instead of Controller

### PR DESCRIPTION
**Pull request by lorenzo**
for loading helpers

### CODE REVIEW

**Comment by dereuromark** [comment]
The one problem I have with AppView is that it is hard to add helpers on top on a per controller/action level.
So far it was easy to add it to the list, but we are using only one AppView per code usually.

**Comment by HavokInspiration** [comment]
@dereuromark Can't the ViewBuilder be used for that purpose ?

**Comment by dereuromark** [comment]
@HavokInspiration Could be. Is that documented so far?

**Comment by HavokInspiration** [comment]
The only place I could find some mention of this is here, the second example : http://book.cakephp.org/3.0/en/views/helpers.html#conditionally-loading-helpers

**Comment by dereuromark** [comment]
The first example makes no sense to me, as I sure dont want it for all actions index, and of course this will introduce way more logic in the AppView than it should have.
But yeah the 2nd example kind of says it: Using that inside actions should continue to work.

**Comment by HavokInspiration** [comment]
I was only talking about the second one. I find the first one arguable as well.

**Comment by jhli** [comment]
For 4.x? we could mobe to PostsView etc also via bake?

Another way would be to have a fcallable being defined on the view but from controlöer context.

This needs to be improved imho. For aliasing Helpers the docs already say to use ApView.

**Comment by markstory** [comment]
> For 4.x? we could mobe to PostsView etc also via bake?

Do you mean view classes per resource? I feel that is a lot of complexity to force on new developers and simple applications.

**Comment by markstory** [comment]
@dereuromark Perhaps we are missing an example on how to use view subclasses per controller? I generally find loading all the helpers is rarely a performance issue and makes applications easier to work with as you don't have to remember which helpers are loaded where.

**Pull request merged**
