### PR TITLE
Update retrieving-your-data.rst

### PR DESCRIPTION
**Pull request by voycey**
There is conflicting information between this page and the pagination documentation for custom finder types as per #7075

### CODE REVIEW

**Comment by dereuromark** [comment]
findType or finder? ( http://book.cakephp.org/3.0/en/controllers/components/pagination.html )

**Comment by ADmad** [comment]
@dereuromark Master branch is for 2.x

**Comment by dereuromark** [comment]
Gotcha, catches me everytime :)

**Comment by markstory** [comment]
One day I'll find the time to switch the branches around. I've not done it yet because the branch switch requires co-ordinating nginx changes too so its not the simplest change to make.

**Pull request merged**
