### PR TITLE
[ja]Fix typo and additional translation

### PR DESCRIPTION
**Pull request by sayakob**

### CODE REVIEW

**Comment by okinaka** [comment]
errors.rst は #5543, #5550, #5564 に対応していませんでした。
今回対応してみますか？

**Comment by sayakob** [comment]
まだ始めたばかりですが、やってみます！
@okinaka

**Comment by okinaka** [comment]
新たに #5620 も追加されました。よろしくお願いします！

**Comment by sayakob** [comment]
追加承知しました！
見づらくなるかもしれません(スミマセン)が、このPRでまとめて対応します。 :cake:

**Comment by dereuromark** [comment]
Please keep the conversation outside of the translated pages 100% english.
This is otherwise impossible for the maintainers to follow.

**Comment by chinpei215** [comment]
Nonsense. What is the benefit of doing that, except for making you satisfied? Let's assume someone said "This word should be translated as '推す'.", and someone else said "No, '敲く' would be better.". There is not much you can do about it if you don't understand Japanese.

I would rather want to say it is unnecessary to use English here when they contribute to the translations. That will make it easy for non-English speakers to start first contributions. And, your word is not accurate; It is **possible** for some **maintainers** - @okinaka or @tenkoma or me, to follow.

**Comment by dereuromark** [comment]
Fair enough then. But then you need to also take care. 2 months, does that mean we can close.

**Comment by chinpei215** [comment]
Then you could ping to @sayakob though.

@sayakob その後、いかがでしょうか？ 
@okinaka 私は一旦この状態でマージしても良いのかなとも思いました。最新版の翻訳ではないのかと思いますが、誤字のある状態よりはよさそうですし。

**Comment by dereuromark** [comment]
As i said: without english at least partially this is hard to understand.
Anyways, I let you take over. You have it all covered.

**Pull request merged**
