### PR TITLE
Remove information regarding use of "dev-master".

### PR DESCRIPTION
**Pull request by ADmad**
This can trip newbies. Experienced devs would be already aware how to use appropriate branche if they need to.

Refs cakephp/cakephp#14023

### CODE REVIEW

**Comment by dereuromark** [comment]
I am somewhat undecided.
Unexpereienced devs otherwise ask all the time how to get latest master if it contains an unreleased fix..

**Comment by ADmad** [comment]
I am going to give a bad analogy here: If you keep a loaded gun accessible to a kid assuming they might need to protect themselves, it's more likely they will shoot themselves instead of an intruder :slightly_smiling_face:.

**Comment by dereuromark** [comment]
By that Definition you should also remove all debug mode info and Hardcode it to false^^
There should be a reasonable line, and the warnings along with the text qualify to not overstep that imo, but give useful help in case of need.
But i am meeh ;)

**Comment by ADmad** [comment]
> But i am meeh ;)

Me too, I don't care whether this is merged or closed :). I was just reacting to the referenced issue.

**Comment by othercorey** [comment]
If kept, I think it could include a quick explanation that it works only for the current release not future versions in development.

**Comment by dereuromark** [comment]
And when this is needed or useful, only temporarilly to include important bugfixes until the stable release comes out.

**Comment by othercorey** [comment]
I am tempted to say just rip it out.  The people who mess with this are likely always inexperienced users and will always get it wrong no matter what we do. They will ask questions regardless of the docs and we can just say "you can point to the dev branch" and let them figure it out.

**Comment by markstory** [comment]
I think we should be optimizing for standard workflows. People going onto dev-master generally know what they are doing and don't need docs.

**Pull request merged**
