### PR TITLE
[pt] Page Database basics

### PR DESCRIPTION
**Pull request by rochamarcelo**

### CODE REVIEW

**Comment by rochamarcelo** [comment]
hey how I can fix the issue ' WARNING: term not in glossary: plugin syntax'?

**Comment by markstory** [comment]
You have to update the glossary list to include that term. See [the english glossary](https://github.com/cakephp/docs/blob/3.0/en/appendices/glossary.rst) for an example.

**Comment by rochamarcelo** [comment]
@markstory passed. Thanks

**Comment by markstory** [comment]
Thank you again.

**Pull request merged**
