### PR TITLE
3.0 Change "Console & Shells" to "Console Shells & Tasks"

### LINKED ISSUE #3427: RFC: Why is the title 'Console & Shells'?
Referring to this page, http://book.cakephp.org/3.0/en/console-and-shells.html

Why is the title of the page and in the left hand sidebar 'Console & Shells' when all the sub-pages are referring to shells? With Cake 3 there isn't even a `Console` folder, so holding onto this seems misleading to me.

I also, when looking for the page, scan the sidebar for 'Shells', as that's what I'm building. 

I would suggest changing it to 'Shells & Tasks` to better label it's content as a manual page about creating shells and shell tasks.

### PR DESCRIPTION
**Pull request by ravage84**
Resolves #3427

Replaces  #3430

(Redo after mistakenly pushed to 3.0 branch directly)

### CODE REVIEW

**Comment by ravage84** [comment]
@markstory big sorry for pushing into 3.0 directly. :bow: 

I guess we can squash these commits into one:
0cebf9feba05299011e5fa40c734862f996d3d52 (actual change, pushed directly into 3.0)
32ffdf77ba8dccd82bf697ee023ac81b7a45e8be (reverted in 3.0)
a524ad097f940920246b6c70e897ddd9ba1caf30 (new change, same as first)

**Comment by antograssiot** [comment]
@ravage84 Doesn't changing only the header of the file console-and-shells.rst would have been enought and avoid changing all url ?

**Comment by ravage84** [comment]
Wasn't sure how the TOCs been build. But that could work, too...

**Comment by markstory** [comment]
Changing the URLs is :cry: as we lose any google juice or incoming links. Additionally it requires an index rebuild which is a manual process.

**Comment by cake17** [comment]
@ravage84 should this be closed and we only change the header of the file console-and-shells.rst ?

**Comment by ravage84** [comment]
@cake17 If this changes the TOC title too, yes.

**Comment by cake17** [comment]
close this with new open #3464 PR

**Pull request closed without merging**
