### PR TITLE
Add specific php version requirements 

### PR DESCRIPTION
**Pull request by tedewen**
as found at http://book.cakephp.org/3.0/en/installation.html

### CODE REVIEW

**Comment by ionas** [comment]
First of all, thanks for contributing back.
I'd link to http://book.cakephp.org/3.0/en/installation.html#requirements instead or http://book.cakephp.org/3.0/en/installation.html#installing-cakephp instead of copying the paragraph.

**Comment by tedewen** [comment]
As one who is a noob and got bitten on the butt by it not being explicit in the 'quickstart' I think it is worth duplicating. The whole rest of this page is duplicated content, in fact it is just these paragraphs and a technical digression that differentiates the two pages. As an honest noob, i probably wouldn't have followed a 'see tech details here' - far too often such links lead to information that is way over my head.

had this been explicit I would have done the check as part of following the quickstart, and would not have had to join IRC, convince the kind people there that all I had done was copy and paste from the quickstart page yet ended up with an old version of cakephp.

You know, ionas, you helped me sort it. :D

/https://github.com/cakephp/app/issues/385#issuecomment-218734079)

**Comment by ionas** [comment]
@markstory I did a quick search but could not find anything. Is there a way to set global constants/variables for Sphinx? That way we could manage minimum versions for things like PHP without updating a lot of different places in the docs.

**Comment by markstory** [comment]
>  Is there a way to set global constants/variables for Sphinx?

Nope. :cry:

**Comment by markstory** [comment]
Thanks @tedewen :tada:

**Pull request merged**
