### PR TITLE
Update 3-0-migration-guide.rst

### PR DESCRIPTION
**Pull request by felipevr**
Tradução em andamento (translation in progress)

### CODE REVIEW

**Comment by andtxr** [comment]
@felipevr Thanks for the help! Right now the portuguese translation need more contributors. Would you like to join us? We have a specific repository for translations, what helps in the revisions before the PRs.

**Comment by markstory** [comment]
@andtxr Would your workflow be easier if someone in the portuguese community had commit access to this repository?

**Comment by andtxr** [comment]
@markstory I'm concluding a page for the Portuguese community to gather new contributors. Next to that, I intend to improve and standardize the flow. Access to the repository would facilitate the reviewing until we get new contributors and the recurring ones adapt to the flow. When sporadic cases arise, it would also be easier take advantage of something that was started but not finished.

**Comment by andtxr** [comment]
I saved and fixed what could be useful from this PR in cakephp-br/docs. :+1:

**Comment by felipevr** [comment]
@andtxr I would be pleased to help translation the cakephp doc to portuguese. Right now I am finishing this page.

**Comment by andtxr** [comment]
@felipevr This is great! would you mind to continue it in [https://github.com/cakephp-br/docs/tree/pt-3-0-migration-guide](https://github.com/cakephp-br/docs/tree/pt-3-0-migration-guide) branch? This way we can work a bit faster.

**Pull request closed without merging**
