### PR TITLE
Fix incorrect markup in associations-linking-models-together.rst

### PR DESCRIPTION
**Pull request by chinpei215**
Remove `<blockquote>` tags. See http://book.cakephp.org/2.0/en/models/associations-linking-models-together.html#hasmany-through-the-join-model

### CODE REVIEW

**Comment by HavokInspiration** [comment]
Good catch @chinpei215 ! 👏

**Comment by chinpei215** [comment]
@HavokInspiration Thanks! But I confess. This issue, #4397, and #4396 were reported by **holywise** in the #japanese slack channel. I should have mentioned it 😛 Thank you **holywise**!

**Comment by HavokInspiration** [comment]
@chinpei215 Don't forget to thank him on our behalf then :)

**Comment by chinpei215** [comment]
@HavokInspiration OK. I'll thank him again in the channel :)

**Pull request merged**
