### PR TITLE
add note for translations way of doing

### PR DESCRIPTION
**Pull request by cake17**
ref to #1713 
add a note on how translations works for docs

### CODE REVIEW

**Comment by cake17** [comment]
Please let me know if you want edits on this

**Comment by markstory** [comment]
Nice work @cake17

**Comment by ravage84** [comment]
Sorry for being late to the show but here are some comments:

https://github.com/cakephp/docs/pull/2550/files#diff-57c701e2395aec4004ed8a648c52070fR42
Shouldn't it be ``Reminder for Docs Administrators`` or at least ``Reminder for Docs Admins``. Or is should it be "Administration"?

https://github.com/cakephp/docs/pull/2550/files#diff-57c701e2395aec4004ed8a648c52070fR28
https://github.com/cakephp/docs/pull/2550/files#diff-57c701e2395aec4004ed8a648c52070fR45
https://github.com/cakephp/docs/pull/2550/files#diff-57c701e2395aec4004ed8a648c52070fR46
https://github.com/cakephp/docs/pull/2550/files#diff-57c701e2395aec4004ed8a648c52070fR49
https://github.com/cakephp/docs/pull/2550/files#diff-57c701e2395aec4004ed8a648c52070fR67
https://github.com/cakephp/docs/pull/2550/files#diff-57c701e2395aec4004ed8a648c52070fR70
Isn't it "English" with a capital E?

https://github.com/cakephp/docs/pull/2550/files#diff-57c701e2395aec4004ed8a648c52070fR51
https://github.com/cakephp/docs/pull/2550/files#diff-57c701e2395aec4004ed8a648c52070fR52
Is there a reason the sentences don't start with a capital letter?

https://github.com/cakephp/docs/pull/2550/files#diff-57c701e2395aec4004ed8a648c52070fR67
Isn't it "refer" instead of "referer"?

Can and will we back port this into the 2.x docs?

**Comment by cake17** [comment]
Reminder for Docs Administrators, English with capital E, capital letter for the list elements and refer would indeed be better to me.
And this can be back ported into 2.x for sure as we also used these "rules" for 2.x book

**Comment by ravage84** [comment]
I'll take care of the corrections

**Comment by ravage84** [comment]
Done in https://github.com/cakephp/docs/commit/97ff2d4e2a9b4a56f1d7135410183504f2af401d

Proposed the backporting in https://github.com/cakephp/docs/pull/2573

**Comment by cake17** [comment]
:+1: well done

**Pull request merged**
