### PR TITLE
[ja] Translated contributing/backwards-compatibility.rst

### PR DESCRIPTION
**Pull request by hiromi2424**
CakeFest Contribution!!!

### CODE REVIEW

**Comment by hiromi2424** [comment]
This translation can be applied to 3.0 branch as well.
Should I send PR for 3.0 branch too?

**Comment by markstory** [comment]
@hiromi2424 We've stopped merging master into 3.0. A separate pull request for 3.0 would be fantastic.

**Comment by markstory** [comment]
The table formatting, might not be right, but I can fix that.

**Comment by markstory** [comment]
Nope, tables look :ok_hand:

**Pull request merged**
