### PR TITLE
add info about cake.po

### PR DESCRIPTION
**Pull request by cake17**
ref to #3469

### CODE REVIEW

**Comment by cake17** [comment]
@6120ssu when you run `cake i18n`, the prompt asks "Would you like to extract the messages from the CakePHP core?", if you answer "yes", a cake.pot is created. So maybe there is no need for changing the path for extracting ?

**Comment by 6120ssu** [comment]
When I executed the i18n extract command, the terminal echoed :
Current paths: None
What is the path you would like to extract?
[Q]uit [D]one

That’s why it may be useful to add the right path for users new to cake.

William Russeil
06 43 33 55 94
 infos@wmc.fr

**Comment by cake17** [comment]
When I run `cake i18n`, after the question `What is the path you would like to extract?`, it suggests me , `/path/to/project/src` so I type `enter`.

I kept the path suggested and after answer `yes` for the question `Would you like to extract the messages from the CakePHP core?`

**Comment by 6120ssu** [comment]
William Russeil
06 43 33 55 94
 infos@wmc.fr




> Le 6 nov. 2015 à 11:21, cake17 <notifications@github.com> a écrit :
> 
> When I run cake i18n, after the question What is the path you would like to extract?, it suggests me , /path/to/project/src so I type enter.
> 
> I kept the path suggested and after answer yes for the question Would you like to extract the messages from the CakePHP core?

This is not the path to the core. We are talking about extracting the core strings in a separate file.
If you type yes and yes again to the following question, you will end up with all strings merged into one single file. This is not what we want.

If you do not type enter at the previous step, it will end up saying :
Current paths: None

**Comment by cake17** [comment]
@6120ssu 

If you answer `No` to `Would you like to merge all domain strings into the default.pot file?`, a single `cake.pot` file with core strings will be created.

The other file `default.pot` is created with only the stuffs from my app (no core strings).

I think the questions of i18n are enough clear. It lets you the choice to merge or not the core strings.

capture d ecran 2015-11-09 a 11 19 37

**Comment by 6120ssu** [comment]
William Russeil
06 43 33 55 94
 infos@wmc.fr




> Le 9 nov. 2015 à 11:35, cake17 <notifications@github.com> a écrit :
> 
> @6120ssu
> 
> If you answer No to Would you like to merge all domain strings into the default.pot file?, a single cake.pot file with core strings will be created.
> 
> The other file default.pot is created with only the stuffs from my app (no core strings).
> 
> I think the questions of i18n are enough clear. It lets you the choice to merge or not the core strings.

I do not agree completely.
The issue I had to face is that it is not documented anywhere.
Of course, once you’ve done it, it is just « a piece of cake ».
But the first time, you are quite puzzled.

**Pull request merged**
