### PR TITLE
Logger class name using logger 'class' constant

### PR DESCRIPTION
**Pull request by andrii-pukhalevych**

### CODE REVIEW

**Comment by dereuromark** [comment]
The advantage of the string is that it doesn't need a use statement.

**Comment by andrii-pukhalevych** [comment]
Yeah, but its also makes not possible to use refactor/find usages features.

Generally I just referenced to https://github.com/cakephp/app/blob/master/config/app.php code.

**Comment by dereuromark** [comment]
Sure, no question there.
I just think that having the doc examples easier to "copy and paste" could be more convenient to most.

But I am fine either way.

**Review by Arhell — COMMENTED** [review]
cc @markstory

**Pull request merged**
