### PR TITLE
fix sphinx build errors, only label & target warning left

### PR DESCRIPTION
**Pull request by cake17**

### CODE REVIEW

**Comment by okinaka** [comment]
Why are there duplicated subtitle "Prevent Sphinx to Output Warnings" in documentation.rst ?

**Comment by cake17** [comment]
Both are notes to prevent warnings with sphinx, but the concerns are different:
- one when a function is referenced in multiple files
- one when we don't need to reference a file in the toc-tree
So both categories are next to their concerns

**Comment by okinaka** [comment]
Thank you for your reply!
Now, I am confused by the difference between master branch and 3.0 branch.
I think it's better to fix difference, but I don't know how to fix there.

**Comment by cake17** [comment]
You're right, I forgot to update 2.x with last changes :smile: 
Is it ok now with 25f0e4f ?

**Comment by okinaka** [comment]
The location of them are different.
3.0 is above "Cross Referencing Links",
but 2.x is above "Cross Referencing".

Is 3.0 right location?

**Comment by cake17** [comment]
My mistake, now it should be ok :smile:

**Pull request merged**
