### PR TITLE
Add link to the brand new forum

### PR DESCRIPTION
**Pull request by jorisvaesen**

### CODE REVIEW

**Comment by dereuromark** [comment]
:+1:

**Comment by ravage84** [comment]
Thanks, @jorisvaesen 
Would you please create a PR for 2.x, too? :bow:

**Comment by jorisvaesen** [comment]
#3932

**Comment by ionas** [comment]
- http://community.cakephp.org/ needs to be updated too
- http://www.cakephp-forum.de/ is quite annoying as the first response on google

**Comment by ravage84** [comment]
@ionas community.cakephp.org is kept in here: https://github.com/cakephp/community.cakephp.org

The Google result you see aren't the same as for other people.
For me, it's the second result on the Swiss Google page.

https://www.google.ch/#hl=de&q=cakephp+forum

It is because our Browsers accept German as language.

**Pull request merged**
