### PR TITLE
Fix: Japanese doc

### PR DESCRIPTION
**Pull request by eltociear**
'ストアドプロシージャ' seems better than 'ストアードプロシージャー'.

### CODE REVIEW

**Comment by okinaka** [comment]
Refs: https://github.com/cakephp/docs/pull/5661#discussion_r174617068

As a result of discussions among the docs-ja team members, it was decided to use words with long vowels as much as possible to ensure consistency.

**Comment by eltociear** [comment]
thanks review.
revert and fixed another document.

**Comment by okinaka** [comment]
Thank you!

**Comment by eltociear** [comment]
Thank you!!

**Pull request merged**
