### PR TITLE
[en] correct origianl text

### PR DESCRIPTION
**Pull request by blackpuppy**
- en/development/testing.rst
- en/development/exceptions.rst

### CODE REVIEW

**Comment by cake17** [comment]
thanks @blackpuppy !

**Comment by blackpuppy** [comment]
Thanks!
Just wonder what happened between build 2243 Jan 27, 2015 2:27:07 AM and build 2244 Jan 27, 2015 2:47:32 AM.  Suspect some change between these 2 builds cause all the following build to fail.

**Comment by cake17** [comment]
It seems that latex generation failed.

Maybe it comes from this commit https://github.com/cakephp/docs/commit/db1c4adc74e9bec0dbe1b56e7db0950724029efc as the build stops after containable behavior.

**Comment by cake17** [comment]
This seems to work now...

**Comment by blackpuppy** [comment]
Great!  Thanks a lot!  Can see my work show up in the cookbook now.  :smiley:

**Pull request merged**
